# Generated by Django 6.1.1 on 2026-09-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Truck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("truck_number", models.CharField(max_length=20, unique=True)),
                ("truck_type", models.CharField(max_length=20)),
                ("capacity", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "compatible_waste_type",
                    models.CharField(
                        choices=[
                            ("dry", "Dry Waste"),
                            ("wet", "Wet Waste"),
                            ("plastic", "Plastic"),
                            ("mixed", "Mixed Waste"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("petrol", "Petrol"),
                            ("diesel", "Diesel"),
                            ("electric", "Electric"),
                        ],
                        max_length=20,
                    ),
                ),
                ("puc", models.DateField()),
            ],
        ),
    ]
