# Generated by Django 6.1.1 on 2026-09-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("truck", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="truck",
            name="puc",
            field=models.DateField(blank=True, null=True),
        ),
    ]
